yumrepo { 'amzn-main':
  ensure          => 'present',
  descr           => 'amzn-main-Base',
  enabled         => '1',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/main/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-main-debuginfo':
  ensure          => 'present',
  descr           => 'amzn-main-debuginfo',
  enabled         => '0',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/main/debuginfo/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-nosrc':
  ensure          => 'present',
  descr           => 'amzn-nosrc-Base',
  enabled         => '0',
  failovermethod  => 'priority',
  gpgcheck        => '0',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/nosrc/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-preview':
  ensure          => 'present',
  descr           => 'amzn-preview-Base',
  enabled         => '0',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/preview/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-preview-debuginfo':
  ensure          => 'present',
  descr           => 'amzn-preview-debuginfo',
  enabled         => '0',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/preview/debuginfo/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-updates':
  ensure          => 'present',
  descr           => 'amzn-updates-Base',
  enabled         => '1',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/updates/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'amzn-updates-debuginfo':
  ensure          => 'present',
  descr           => 'amzn-updates-debuginfo',
  enabled         => '0',
  failovermethod  => 'priority',
  gpgcheck        => '1',
  gpgkey          => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-ga',
  metadata_expire => '300',
  mirrorlist      => 'http://repo.$awsregion.$awsdomain/$releasever/updates/debuginfo/mirror.list',
  priority        => '10',
  retries         => '5',
  timeout         => '10',
}
yumrepo { 'epel':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - $basearch',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch',
}
yumrepo { 'epel-debuginfo':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - $basearch - Debug',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=epel-debug-6&arch=$basearch',
}
yumrepo { 'epel-source':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - $basearch - Source',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=epel-source-6&arch=$basearch',
}
yumrepo { 'epel-testing':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - Testing - $basearch',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=testing-epel6&arch=$basearch',
}
yumrepo { 'epel-testing-debuginfo':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - Testing - $basearch - Debug',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=testing-debug-epel6&arch=$basearch',
}
yumrepo { 'epel-testing-source':
  ensure         => 'present',
  descr          => 'Extra Packages for Enterprise Linux 6 - Testing - $basearch - Source',
  enabled        => '0',
  failovermethod => 'priority',
  gpgcheck       => '1',
  gpgkey         => 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6',
  mirrorlist     => 'https://mirrors.fedoraproject.org/metalink?repo=testing-source-epel6&arch=$basearch',
}
